import { useState } from 'react';
import {
    Dialog,
    DialogContent,
    DialogDescription,
    DialogFooter,
    DialogHeader,
    DialogTitle,
    DialogTrigger,
} from '@/components/ui/dialog';
import { Button } from '@/components/ui/button';
import { FileText, Download, Loader2 } from 'lucide-react';
import { useToast } from '@/hooks/use-toast';

interface Project {
    id: string;
    name: string;
    source_person: string | null;
    budget: number;
    spent: number;
    status: string;
    tax_treatment: string | null;
    created_at: string;
    completed_at: string | null;
}

interface ProjectReceipt {
    id: string;
    description: string;
    amount: number;
    category: string | null;
    created_at: string;
}

interface ProjectStatementDialogProps {
    project: Project;
    receipts: ProjectReceipt[];
}

export default function ProjectStatementDialog({ project, receipts }: ProjectStatementDialogProps) {
    const { toast } = useToast();
    const [open, setOpen] = useState(false);
    const [downloading, setDownloading] = useState(false);

    const formatCurrency = (amount: number): string => {
        return new Intl.NumberFormat('en-NG', {
            style: 'currency',
            currency: 'NGN',
            minimumFractionDigits: 0,
            maximumFractionDigits: 0,
        }).format(amount);
    };

    const formatDate = (date: string): string => {
        return new Date(date).toLocaleDateString('en-NG', {
            year: 'numeric',
            month: 'long',
            day: 'numeric',
        });
    };

    const generateStatementHTML = (): string => {
        const balance = project.budget - project.spent;
        const isOverBudget = balance < 0;

        return `
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>Project Statement - ${project.name}</title>
  <style>
    body { font-family: 'Segoe UI', Arial, sans-serif; max-width: 800px; margin: 0 auto; padding: 40px; color: #1a1a1a; }
    .header { text-align: center; border-bottom: 2px solid #10b981; padding-bottom: 20px; margin-bottom: 30px; }
    .header h1 { color: #10b981; margin: 0 0 10px 0; font-size: 28px; }
    .header .subtitle { color: #666; font-size: 14px; }
    .section { margin-bottom: 30px; }
    .section-title { font-size: 16px; font-weight: 600; color: #374151; border-bottom: 1px solid #e5e7eb; padding-bottom: 8px; margin-bottom: 15px; }
    .info-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 15px; }
    .info-item { background: #f9fafb; padding: 12px; border-radius: 8px; }
    .info-label { font-size: 12px; color: #6b7280; margin-bottom: 4px; }
    .info-value { font-size: 16px; font-weight: 500; }
    .summary-grid { display: grid; grid-template-columns: repeat(3, 1fr); gap: 20px; text-align: center; }
    .summary-item { background: #f0fdf4; padding: 20px; border-radius: 12px; }
    .summary-label { font-size: 12px; color: #6b7280; }
    .summary-value { font-size: 24px; font-weight: 700; color: #10b981; margin-top: 5px; }
    .summary-value.negative { color: #ef4444; }
    table { width: 100%; border-collapse: collapse; margin-top: 15px; }
    th, td { padding: 12px; text-align: left; border-bottom: 1px solid #e5e7eb; }
    th { background: #f9fafb; font-weight: 600; color: #374151; font-size: 12px; text-transform: uppercase; }
    td { font-size: 14px; }
    .amount { text-align: right; font-weight: 500; }
    .footer { margin-top: 40px; padding-top: 20px; border-top: 1px solid #e5e7eb; text-align: center; color: #9ca3af; font-size: 12px; }
    .tax-notice { background: #fef3c7; padding: 15px; border-radius: 8px; margin-top: 20px; font-size: 13px; color: #92400e; }
    @media print { body { padding: 20px; } }
  </style>
</head>
<body>
  <div class="header">
    <h1>📋 Project Statement</h1>
    <div class="subtitle">Generated by PRISM on ${formatDate(new Date().toISOString())}</div>
  </div>

  <div class="section">
    <div class="section-title">Project Details</div>
    <div class="info-grid">
      <div class="info-item">
        <div class="info-label">Project Name</div>
        <div class="info-value">${project.name}</div>
      </div>
      <div class="info-item">
        <div class="info-label">Fund Source</div>
        <div class="info-value">${project.source_person || 'Not specified'}</div>
      </div>
      <div class="info-item">
        <div class="info-label">Created</div>
        <div class="info-value">${formatDate(project.created_at)}</div>
      </div>
      <div class="info-item">
        <div class="info-label">Status</div>
        <div class="info-value" style="text-transform: capitalize;">${project.status}</div>
      </div>
    </div>
  </div>

  <div class="section">
    <div class="section-title">Financial Summary</div>
    <div class="summary-grid">
      <div class="summary-item">
        <div class="summary-label">Total Budget</div>
        <div class="summary-value">${formatCurrency(project.budget)}</div>
      </div>
      <div class="summary-item">
        <div class="summary-label">Total Spent</div>
        <div class="summary-value">${formatCurrency(project.spent)}</div>
      </div>
      <div class="summary-item">
        <div class="summary-label">Balance</div>
        <div class="summary-value ${isOverBudget ? 'negative' : ''}">${formatCurrency(balance)}</div>
      </div>
    </div>
    ${project.tax_treatment === 'non_taxable' ? `
    <div class="tax-notice">
      <strong>📌 Tax Note:</strong> This project is classified as an agency/third-party fund under Section 5 of the Nigeria Tax Act 2025. 
      These funds are held on behalf of another party and are not considered taxable income, provided proper documentation is maintained.
    </div>
    ` : ''}
  </div>

  ${receipts.length > 0 ? `
  <div class="section">
    <div class="section-title">Expense Breakdown (${receipts.length} items)</div>
    <table>
      <thead>
        <tr>
          <th>Date</th>
          <th>Description</th>
          <th>Category</th>
          <th class="amount">Amount</th>
        </tr>
      </thead>
      <tbody>
        ${receipts.map(r => `
        <tr>
          <td>${formatDate(r.created_at)}</td>
          <td>${r.description}</td>
          <td>${r.category || 'Uncategorized'}</td>
          <td class="amount">${formatCurrency(r.amount)}</td>
        </tr>
        `).join('')}
        <tr style="font-weight: 600; background: #f9fafb;">
          <td colspan="3">Total Expenses</td>
          <td class="amount">${formatCurrency(receipts.reduce((sum, r) => sum + r.amount, 0))}</td>
        </tr>
      </tbody>
    </table>
  </div>
  ` : `
  <div class="section">
    <div class="section-title">Expense Breakdown</div>
    <p style="color: #9ca3af; text-align: center; padding: 30px;">No expenses recorded for this project yet.</p>
  </div>
  `}

  <div class="footer">
    <p>This statement was automatically generated by PRISM Tax Assistant.</p>
    <p>For questions about this project, contact your tax advisor or reach out via Telegram/WhatsApp.</p>
  </div>
</body>
</html>
    `;
    };

    const handleDownload = async () => {
        setDownloading(true);
        try {
            const html = generateStatementHTML();
            const blob = new Blob([html], { type: 'text/html' });
            const url = URL.createObjectURL(blob);
            const a = document.createElement('a');
            a.href = url;
            a.download = `project-statement-${project.name.replace(/[^a-z0-9]/gi, '-').toLowerCase()}.html`;
            document.body.appendChild(a);
            a.click();
            document.body.removeChild(a);
            URL.revokeObjectURL(url);

            toast({
                title: 'Statement Downloaded',
                description: 'Open the file in a browser and print to PDF if needed.',
            });
            setOpen(false);
        } catch (error) {
            console.error('Download error:', error);
            toast({
                title: 'Download Failed',
                description: 'Could not generate statement',
                variant: 'destructive',
            });
        } finally {
            setDownloading(false);
        }
    };

    return (
        <Dialog open={open} onOpenChange={setOpen}>
            <DialogTrigger asChild>
                <Button variant="outline" size="sm">
                    <FileText className="h-4 w-4 mr-2" />
                    Generate Statement
                </Button>
            </DialogTrigger>
            <DialogContent className="sm:max-w-[500px]">
                <DialogHeader>
                    <DialogTitle>Project Statement</DialogTitle>
                    <DialogDescription>
                        Generate a formal statement for "{project.name}" showing budget, expenses, and balance.
                    </DialogDescription>
                </DialogHeader>

                <div className="py-4 space-y-4">
                    <div className="bg-accent/50 rounded-lg p-4">
                        <div className="grid grid-cols-3 gap-4 text-center">
                            <div>
                                <p className="text-xs text-muted-foreground">Budget</p>
                                <p className="font-medium">{formatCurrency(project.budget)}</p>
                            </div>
                            <div>
                                <p className="text-xs text-muted-foreground">Spent</p>
                                <p className="font-medium">{formatCurrency(project.spent)}</p>
                            </div>
                            <div>
                                <p className="text-xs text-muted-foreground">Balance</p>
                                <p className={`font-medium ${project.budget - project.spent < 0 ? 'text-red-500' : 'text-emerald-600'}`}>
                                    {formatCurrency(project.budget - project.spent)}
                                </p>
                            </div>
                        </div>
                    </div>

                    <p className="text-sm text-muted-foreground">
                        The statement will include {receipts.length} expense record{receipts.length !== 1 ? 's' : ''}
                        and can be used for:
                    </p>
                    <ul className="text-sm text-muted-foreground list-disc pl-5 space-y-1">
                        <li>Client reporting and transparency</li>
                        <li>Tax documentation (Section 5 compliance)</li>
                        <li>Audit trail for agency funds</li>
                    </ul>
                </div>

                <DialogFooter>
                    <Button variant="outline" onClick={() => setOpen(false)}>
                        Cancel
                    </Button>
                    <Button onClick={handleDownload} disabled={downloading}>
                        {downloading ? (
                            <Loader2 className="h-4 w-4 mr-2 animate-spin" />
                        ) : (
                            <Download className="h-4 w-4 mr-2" />
                        )}
                        Download Statement
                    </Button>
                </DialogFooter>
            </DialogContent>
        </Dialog>
    );
}
